name: industry_maintenance_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_it: ^7.6.6
  go_router: ^13.0.0
  hooked_bloc: ^1.4.3
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  linteo: ^1.1.0

flutter:
  uses-material-design: true
