// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf0cYiyDn8j2bgddHRw4BxvmwEfY-LKjA',
    appId: '1:618146169101:web:248ea183d34e0bce54f044',
    messagingSenderId: '618146169101',
    projectId: 'ur-app-8640c',
    authDomain: 'ur-app-8640c.firebaseapp.com',
    storageBucket: 'ur-app-8640c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5njn_ZYOaJGhja4AIXUw2UbUluJNLapo',
    appId: '1:618146169101:android:a641895f9250fe8654f044',
    messagingSenderId: '618146169101',
    projectId: 'ur-app-8640c',
    storageBucket: 'ur-app-8640c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9rTiTBILFkVEENXrGZUEaJc8rwxtJFpA',
    appId: '1:618146169101:ios:596967e947541ff954f044',
    messagingSenderId: '618146169101',
    projectId: 'ur-app-8640c',
    storageBucket: 'ur-app-8640c.appspot.com',
    iosBundleId: 'com.dominikgrosser.industryMaintenanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9rTiTBILFkVEENXrGZUEaJc8rwxtJFpA',
    appId: '1:618146169101:ios:1f46617918db662554f044',
    messagingSenderId: '618146169101',
    projectId: 'ur-app-8640c',
    storageBucket: 'ur-app-8640c.appspot.com',
    iosBundleId: 'com.dominikgrosser.industryMaintenanceApp.RunnerTests',
  );
}
